import { Injectable, signal } from '@angular/core';
import { User } from '../../models';

@Injectable({
  providedIn: 'root',
})
export class UsersService {
  private users = signal<User[]>([
    { id: '1', name: 'John Doe', email: 'john@example.com', role: 'Admin', status: 'Active' },
    { id: '2', name: 'Jane Smith', email: 'jane@example.com', role: 'Editor', status: 'Active' },
    { id: '3', name: 'Bob Wilson', email: 'bob@example.com', role: 'Viewer', status: 'Inactive' },
    { id: '4', name: 'Alice Johnson', email: 'alice@example.com', role: 'Admin', status: 'Active' },
    { id: '5', name: 'Mike Brown', email: 'mike@example.com', role: 'Editor', status: 'Active' },
    { id: '6', name: 'Sarah Davis', email: 'sarah@example.com', role: 'Viewer', status: 'Active' },
    { id: '7', name: 'Tom Miller', email: 'tom@example.com', role: 'Editor', status: 'Inactive' },
    { id: '8', name: 'Lisa Garcia', email: 'lisa@example.com', role: 'Viewer', status: 'Active' },
    {
      id: '9',
      name: 'David Martinez',
      email: 'david@example.com',
      role: 'Admin',
      status: 'Active',
    },
    { id: '10', name: 'Emma Wilson', email: 'emma@example.com', role: 'Editor', status: 'Active' },
    {
      id: '11',
      name: 'James Anderson',
      email: 'james@example.com',
      role: 'Viewer',
      status: 'Inactive',
    },
    {
      id: '12',
      name: 'Olivia Taylor',
      email: 'olivia@example.com',
      role: 'Editor',
      status: 'Active',
    },
    {
      id: '13',
      name: 'William Thomas',
      email: 'william@example.com',
      role: 'Admin',
      status: 'Active',
    },
    {
      id: '14',
      name: 'Sophia Jackson',
      email: 'sophia@example.com',
      role: 'Viewer',
      status: 'Active',
    },
    {
      id: '15',
      name: 'Benjamin White',
      email: 'benjamin@example.com',
      role: 'Editor',
      status: 'Active',
    },
    {
      id: '16',
      name: 'Isabella Harris',
      email: 'isabella@example.com',
      role: 'Viewer',
      status: 'Inactive',
    },
    { id: '17', name: 'Lucas Martin', email: 'lucas@example.com', role: 'Admin', status: 'Active' },
    { id: '18', name: 'Mia Thompson', email: 'mia@example.com', role: 'Editor', status: 'Active' },
    {
      id: '19',
      name: 'Henry Garcia',
      email: 'henry@example.com',
      role: 'Viewer',
      status: 'Active',
    },
    {
      id: '20',
      name: 'Charlotte Martinez',
      email: 'charlotte@example.com',
      role: 'Editor',
      status: 'Active',
    },
    {
      id: '21',
      name: 'Alexander Robinson',
      email: 'alexander@example.com',
      role: 'Admin',
      status: 'Inactive',
    },
    {
      id: '22',
      name: 'Amelia Clark',
      email: 'amelia@example.com',
      role: 'Viewer',
      status: 'Active',
    },
    {
      id: '23',
      name: 'Sebastian Rodriguez',
      email: 'sebastian@example.com',
      role: 'Editor',
      status: 'Active',
    },
    {
      id: '24',
      name: 'Harper Lewis',
      email: 'harper@example.com',
      role: 'Viewer',
      status: 'Active',
    },
    { id: '25', name: 'Mason Lee', email: 'mason@example.com', role: 'Admin', status: 'Active' },
    {
      id: '26',
      name: 'Evelyn Walker',
      email: 'evelyn@example.com',
      role: 'Editor',
      status: 'Inactive',
    },
    { id: '27', name: 'Ethan Hall', email: 'ethan@example.com', role: 'Viewer', status: 'Active' },
    {
      id: '28',
      name: 'Abigail Allen',
      email: 'abigail@example.com',
      role: 'Editor',
      status: 'Active',
    },
    { id: '29', name: 'Logan Young', email: 'logan@example.com', role: 'Admin', status: 'Active' },
    {
      id: '30',
      name: 'Emily Hernandez',
      email: 'emily@example.com',
      role: 'Viewer',
      status: 'Active',
    },
    { id: '31', name: 'Jacob King', email: 'jacob@example.com', role: 'Editor', status: 'Active' },
    {
      id: '32',
      name: 'Elizabeth Wright',
      email: 'elizabeth@example.com',
      role: 'Viewer',
      status: 'Inactive',
    },
    {
      id: '33',
      name: 'Jackson Lopez',
      email: 'jackson@example.com',
      role: 'Admin',
      status: 'Active',
    },
    { id: '34', name: 'Sofia Hill', email: 'sofia@example.com', role: 'Editor', status: 'Active' },
    { id: '35', name: 'Aiden Scott', email: 'aiden@example.com', role: 'Viewer', status: 'Active' },
    { id: '36', name: 'Avery Green', email: 'avery@example.com', role: 'Editor', status: 'Active' },
    { id: '37', name: 'Luke Adams', email: 'luke@example.com', role: 'Admin', status: 'Inactive' },
    { id: '38', name: 'Ella Baker', email: 'ella@example.com', role: 'Viewer', status: 'Active' },
    {
      id: '39',
      name: 'Carter Gonzalez',
      email: 'carter@example.com',
      role: 'Editor',
      status: 'Active',
    },
    {
      id: '40',
      name: 'Scarlett Nelson',
      email: 'scarlett@example.com',
      role: 'Viewer',
      status: 'Active',
    },
    { id: '41', name: 'Owen Carter', email: 'owen@example.com', role: 'Admin', status: 'Active' },
    {
      id: '42',
      name: 'Madison Mitchell',
      email: 'madison@example.com',
      role: 'Editor',
      status: 'Active',
    },
    {
      id: '43',
      name: 'Wyatt Perez',
      email: 'wyatt@example.com',
      role: 'Viewer',
      status: 'Inactive',
    },
    {
      id: '44',
      name: 'Layla Roberts',
      email: 'layla@example.com',
      role: 'Editor',
      status: 'Active',
    },
    {
      id: '45',
      name: 'Grayson Turner',
      email: 'grayson@example.com',
      role: 'Admin',
      status: 'Active',
    },
    {
      id: '46',
      name: 'Chloe Phillips',
      email: 'chloe@example.com',
      role: 'Viewer',
      status: 'Active',
    },
    { id: '47', name: 'Leo Campbell', email: 'leo@example.com', role: 'Editor', status: 'Active' },
    { id: '48', name: 'Zoey Parker', email: 'zoey@example.com', role: 'Viewer', status: 'Active' },
    {
      id: '49',
      name: 'Jayden Evans',
      email: 'jayden@example.com',
      role: 'Admin',
      status: 'Inactive',
    },
    { id: '50', name: 'Nora Edwards', email: 'nora@example.com', role: 'Editor', status: 'Active' },
    {
      id: '51',
      name: 'Gabriel Collins',
      email: 'gabriel@example.com',
      role: 'Viewer',
      status: 'Active',
    },
    { id: '52', name: 'Lily Stewart', email: 'lily@example.com', role: 'Editor', status: 'Active' },
    {
      id: '53',
      name: 'Julian Sanchez',
      email: 'julian@example.com',
      role: 'Admin',
      status: 'Active',
    },
    {
      id: '54',
      name: 'Hannah Morris',
      email: 'hannah@example.com',
      role: 'Viewer',
      status: 'Inactive',
    },
    {
      id: '55',
      name: 'Mateo Rogers',
      email: 'mateo@example.com',
      role: 'Editor',
      status: 'Active',
    },
  ]);

  getUsers = this.users.asReadonly();
}
